### ISSUE TITLE
Agregar textura al terreno (suelo)

### ISSUE THREAD

**Issue by FScaccheri** [dylanalvarez/tp2-sistemas-graficos#10]
- Combinar al menos dos tipos de de mapas difusos (pasto y tierra) para generar una variación irregular
- Usar algún tipo de lógica o algoritmo en el shader (máscara, ruido perlin, etc)

**Comment by dylanalvarez** [comment]
queda en TODO:

Cargar 2 texturas al mismo tiempo
Agregar algoritmo de ruido/mascara/etc https://cpetry.github.io/TextureGenerator-Online/
